"""
ui/themes.py
------------
Central theme definitions for Professional GPA Suite.
"""

from copy import deepcopy

FONTS = {
    "title": ("Segoe UI", 20, "bold"),
    "heading": ("Segoe UI", 13, "bold"),
    "subhead": ("Segoe UI", 11, "bold"),
    "body": ("Segoe UI", 10),
    "small": ("Segoe UI", 9),
    "mono": ("Consolas", 10),
    "badge": ("Segoe UI", 9, "bold"),
}


def _theme(name: str, **colors):
    theme = {
        "name": name,
        "window_bg": colors["window_bg"],
        "bg": colors["window_bg"],
        "navbar_bg": colors["surface"],
        "sidebar_bg": colors["surface"],
        "surface": colors["surface"],
        "surface_alt": colors["surface_alt"],
        "surface2": colors["surface_alt"],
        "surface_soft": colors["surface_soft"],
        "surface_elevated": colors["surface"],
        "border": colors["border"],
        "border_strong": colors["border_strong"],
        "text": colors["text"],
        "fg": colors["text"],
        "text_muted": colors["text_muted"],
        "fg_muted": colors["text_muted"],
        "text_soft": colors["text_soft"],
        "fg_light": colors["text_soft"],
        "accent": colors["accent"],
        "accent_hover": colors["accent_hover"],
        "accent_soft": colors["accent_soft"],
        "accent_light": colors["accent_light"],
        "accent_fg": colors["accent_fg"],
        "on_accent": colors["accent_fg"],
        "success": colors["success"],
        "success_hover": colors["success_hover"],
        "success_bg": colors["success_bg"],
        "warning": colors["warning"],
        "warning_hover": colors["warning_hover"],
        "warning_bg": colors["warning_bg"],
        "danger": colors["danger"],
        "danger_hover": colors["danger_hover"],
        "danger_bg": colors["danger_bg"],
        "info": colors["info"],
        "info_bg": colors["info_bg"],
        "purple": colors["purple"],
        "purple_bg": colors["purple_bg"],
        "teal": colors["teal"],
        "teal_bg": colors["teal_bg"],
        "amber": colors["amber"],
        "amber_bg": colors["amber_bg"],
        "brown": colors["brown"],
        "brown_bg": colors["brown_bg"],
        "placeholder": colors["placeholder"],
        "hint_bg": colors["hint_bg"],
        "hint_fg": colors["hint_fg"],
        "status_bg": colors["status_bg"],
        "status_fg": colors["status_fg"],
        "status_muted": colors["status_muted"],
        "statusbar": colors["status_bg"],
        "statusbar_fg": colors["status_fg"],
        "footer_bg": colors["footer_bg"],
        "footer_fg": colors["footer_fg"],
        "tab_bar_bg": colors["tab_bar_bg"],
        "tab_bg": colors["tab_bg"],
        "tab_fg": colors["tab_fg"],
        "tab_hover_bg": colors["tab_hover_bg"],
        "tab_active_bg": colors["tab_active_bg"],
        "tab_active_fg": colors["tab_active_fg"],
        "tab_border": colors["tab_border"],
        "entry_bg": colors["entry_bg"],
        "entry_fg": colors["entry_fg"],
        "entry_border": colors["entry_border"],
        "entry_focus": colors["entry_focus"],
        "entry_warning_bg": colors["entry_warning_bg"],
        "entry_success_bg": colors["entry_success_bg"],
        "entry_info_bg": colors["entry_info_bg"],
        "card_bg": colors["card_bg"],
        "card_alt_bg": colors["card_alt_bg"],
        "card_border": colors["card_border"],
        "card_header_bg": colors["card_header_bg"],
        "card_header_fg": colors["card_header_fg"],
        "table_header_bg": colors["table_header_bg"],
        "table_header_fg": colors["table_header_fg"],
        "table_bg": colors["table_bg"],
        "table_alt_bg": colors["table_alt_bg"],
        "table_selected_bg": colors["table_selected_bg"],
        "table_selected_fg": colors["table_selected_fg"],
        "tree_bg": colors["table_bg"],
        "tree_alt_bg": colors["table_alt_bg"],
        "row_alt": colors["table_alt_bg"],
        "tree_heading_bg": colors["table_header_bg"],
        "tree_heading_fg": colors["table_header_fg"],
        "tree_selected_bg": colors["table_selected_bg"],
        "tree_selected_fg": colors["table_selected_fg"],
        "scrollbar_bg": colors["scrollbar_bg"],
        "scrollbar_trough": colors["scrollbar_trough"],
        "scrollbar_active": colors["scrollbar_active"],
        "scrollbar_fg": colors["scrollbar_fg"],
        "button_primary_bg": colors["button_primary_bg"],
        "button_primary_hover": colors["button_primary_hover"],
        "button_primary_fg": colors["button_primary_fg"],
        "button_secondary_bg": colors["button_secondary_bg"],
        "button_secondary_hover": colors["button_secondary_hover"],
        "button_secondary_fg": colors["button_secondary_fg"],
        "button_success_bg": colors["button_success_bg"],
        "button_success_hover": colors["button_success_hover"],
        "button_success_fg": colors["button_success_fg"],
        "button_danger_bg": colors["button_danger_bg"],
        "button_danger_hover": colors["button_danger_hover"],
        "button_danger_fg": colors["button_danger_fg"],
        "button_muted_bg": colors["button_muted_bg"],
        "button_muted_hover": colors["button_muted_hover"],
        "button_muted_fg": colors["button_muted_fg"],
        "button_ghost_bg": colors["button_ghost_bg"],
        "button_ghost_hover": colors["button_ghost_hover"],
        "button_ghost_fg": colors["button_ghost_fg"],
        "gpa_card_bg": colors["gpa_card_bg"],
        "gpa_card_fg": colors["gpa_card_fg"],
        "grade_card_bg": colors["grade_card_bg"],
        "grade_card_fg": colors["grade_card_fg"],
        "points_card_bg": colors["points_card_bg"],
        "points_card_fg": colors["points_card_fg"],
        "info_card_bg": colors["info_card_bg"],
        "info_card_fg": colors["info_card_fg"],
        "strategy_balanced": colors["strategy_balanced"],
        "strategy_progressive": colors["strategy_progressive"],
        "strategy_flexible": colors["strategy_flexible"],
        "strategy_front_loaded": colors["strategy_front_loaded"],
    }
    return theme


THEMES = {
    "light": _theme(
        "light",
        window_bg="#eef3f9",
        surface="#ffffff",
        surface_alt="#f8fbff",
        surface_soft="#f2f6fb",
        border="#d7e1ee",
        border_strong="#b9c7d8",
        text="#0f172a",
        text_muted="#5f6f86",
        text_soft="#8a9ab1",
        accent="#2563eb",
        accent_hover="#1d4ed8",
        accent_soft="#dbeafe",
        accent_light="#eff6ff",
        accent_fg="#ffffff",
        success="#16a34a",
        success_hover="#15803d",
        success_bg="#edfdf3",
        warning="#d97706",
        warning_hover="#b45309",
        warning_bg="#fff7e6",
        danger="#dc2626",
        danger_hover="#b91c1c",
        danger_bg="#fef2f2",
        info="#0284c7",
        info_bg="#e8f4fd",
        purple="#7c3aed",
        purple_bg="#f3f0ff",
        teal="#0891b2",
        teal_bg="#ecfeff",
        amber="#b45309",
        amber_bg="#fff3e0",
        brown="#92400e",
        brown_bg="#fff7eb",
        placeholder="#aab4c0",
        hint_bg="#fffbeb",
        hint_fg="#92400e",
        status_bg="#2563eb",
        status_fg="#ffffff",
        status_muted="#dbeafe",
        footer_bg="#2563eb",
        footer_fg="#ffffff",
        tab_bar_bg="#edf3fb",
        tab_bg="#ffffff",
        tab_fg="#50617b",
        tab_hover_bg="#e8f1ff",
        tab_active_bg="#2563eb",
        tab_active_fg="#ffffff",
        tab_border="#c5d0df",
        entry_bg="#ffffff",
        entry_fg="#0f172a",
        entry_border="#c8d2e2",
        entry_focus="#2563eb",
        entry_warning_bg="#fff9e6",
        entry_success_bg="#f0fff4",
        entry_info_bg="#e8f4fd",
        card_bg="#ffffff",
        card_alt_bg="#f8fbff",
        card_border="#dde5f1",
        card_header_bg="#2563eb",
        card_header_fg="#ffffff",
        table_header_bg="#2563eb",
        table_header_fg="#ffffff",
        table_bg="#ffffff",
        table_alt_bg="#f8fbff",
        table_selected_bg="#dbeafe",
        table_selected_fg="#0f172a",
        scrollbar_bg="#cbd5e1",
        scrollbar_trough="#eef3fb",
        scrollbar_active="#94a3b8",
        scrollbar_fg="#50617b",
        button_primary_bg="#2563eb",
        button_primary_hover="#1d4ed8",
        button_primary_fg="#ffffff",
        button_secondary_bg="#f8fafc",
        button_secondary_hover="#eef2f7",
        button_secondary_fg="#0f172a",
        button_success_bg="#16a34a",
        button_success_hover="#15803d",
        button_success_fg="#ffffff",
        button_danger_bg="#dc2626",
        button_danger_hover="#b91c1c",
        button_danger_fg="#ffffff",
        button_muted_bg="#64748b",
        button_muted_hover="#475569",
        button_muted_fg="#ffffff",
        button_ghost_bg="#f8fafc",
        button_ghost_hover="#eef2f7",
        button_ghost_fg="#5f6f86",
        gpa_card_bg="#e8f4fd",
        gpa_card_fg="#2563eb",
        grade_card_bg="#edf7ee",
        grade_card_fg="#16a34a",
        points_card_bg="#f3f0ff",
        points_card_fg="#7c3aed",
        info_card_bg="#fff7e6",
        info_card_fg="#92400e",
        strategy_balanced="#2563eb",
        strategy_progressive="#7c3aed",
        strategy_flexible="#0891b2",
        strategy_front_loaded="#b45309",
    ),
    "dark": _theme(
        "dark",
        window_bg="#0f172a",
        surface="#111c2e",
        surface_alt="#162338",
        surface_soft="#0d1625",
        border="#2b3a53",
        border_strong="#3a4f6f",
        text="#e5eefb",
        text_muted="#9db2ce",
        text_soft="#7b8da6",
        accent="#4ea1ff",
        accent_hover="#2f7be8",
        accent_soft="#173454",
        accent_light="#1e3350",
        accent_fg="#ffffff",
        success="#34d399",
        success_hover="#22c55e",
        success_bg="#0f2e25",
        warning="#fbbf24",
        warning_hover="#f59e0b",
        warning_bg="#2c230e",
        danger="#f87171",
        danger_hover="#ef4444",
        danger_bg="#35161b",
        info="#38bdf8",
        info_bg="#10283d",
        purple="#a78bfa",
        purple_bg="#23143d",
        teal="#22d3ee",
        teal_bg="#102d3b",
        amber="#f59e0b",
        amber_bg="#2b230f",
        brown="#d97706",
        brown_bg="#2a1e12",
        placeholder="#7f8ea6",
        hint_bg="#241b0e",
        hint_fg="#ffcf7a",
        status_bg="#111c2e",
        status_fg="#d7e6fb",
        status_muted="#8fb0d4",
        footer_bg="#111c2e",
        footer_fg="#8fb0d4",
        tab_bar_bg="#0f172a",
        tab_bg="#111c2e",
        tab_fg="#9db2ce",
        tab_hover_bg="#16263d",
        tab_active_bg="#4ea1ff",
        tab_active_fg="#09101c",
        tab_border="#5a6b86",
        entry_bg="#162131",
        entry_fg="#e5eefb",
        entry_border="#30415a",
        entry_focus="#4ea1ff",
        entry_warning_bg="#2a2414",
        entry_success_bg="#10261d",
        entry_info_bg="#10283d",
        card_bg="#111c2e",
        card_alt_bg="#162338",
        card_border="#2b3a53",
        card_header_bg="#1d3350",
        card_header_fg="#ffffff",
        table_header_bg="#2563eb",
        table_header_fg="#ffffff",
        table_bg="#111c2e",
        table_alt_bg="#162338",
        table_selected_bg="#1e3a5f",
        table_selected_fg="#ffffff",
        scrollbar_bg="#354861",
        scrollbar_trough="#0b1220",
        scrollbar_active="#4c627d",
        scrollbar_fg="#d7e6fb",
        button_primary_bg="#4ea1ff",
        button_primary_hover="#2f7be8",
        button_primary_fg="#ffffff",
        button_secondary_bg="#162131",
        button_secondary_hover="#203049",
        button_secondary_fg="#e5eefb",
        button_success_bg="#22c55e",
        button_success_hover="#16a34a",
        button_success_fg="#ffffff",
        button_danger_bg="#f87171",
        button_danger_hover="#ef4444",
        button_danger_fg="#ffffff",
        button_muted_bg="#475569",
        button_muted_hover="#334155",
        button_muted_fg="#ffffff",
        button_ghost_bg="#0f172a",
        button_ghost_hover="#162338",
        button_ghost_fg="#9db2ce",
        gpa_card_bg="#10283d",
        gpa_card_fg="#4ea1ff",
        grade_card_bg="#10261d",
        grade_card_fg="#34d399",
        points_card_bg="#23143d",
        points_card_fg="#a78bfa",
        info_card_bg="#162338",
        info_card_fg="#9db2ce",
        strategy_balanced="#4ea1ff",
        strategy_progressive="#a78bfa",
        strategy_flexible="#22d3ee",
        strategy_front_loaded="#f59e0b",
    ),
    "blue": _theme(
        "blue",
        window_bg="#08111f",
        surface="#0f1d34",
        surface_alt="#0c1830",
        surface_soft="#0b1629",
        border="#1c3867",
        border_strong="#2b4f8d",
        text="#e2f2ff",
        text_muted="#8bcdf4",
        text_soft="#5db4e5",
        accent="#38bdf8",
        accent_hover="#0ea5e9",
        accent_soft="#0f2e4d",
        accent_light="#113559",
        accent_fg="#ffffff",
        success="#34d399",
        success_hover="#22c55e",
        success_bg="#0d2a22",
        warning="#fbbf24",
        warning_hover="#f59e0b",
        warning_bg="#2d240d",
        danger="#fb7185",
        danger_hover="#f43f5e",
        danger_bg="#34131b",
        info="#38bdf8",
        info_bg="#0f2e4d",
        purple="#a78bfa",
        purple_bg="#23143d",
        teal="#22d3ee",
        teal_bg="#102d3b",
        amber="#f59e0b",
        amber_bg="#2b230f",
        brown="#d97706",
        brown_bg="#2a1e12",
        placeholder="#7dd3fc",
        hint_bg="#0f2239",
        hint_fg="#fbbf24",
        status_bg="#0c1f3a",
        status_fg="#7dd3fc",
        status_muted="#9bd7ff",
        footer_bg="#0c1f3a",
        footer_fg="#7dd3fc",
        tab_bar_bg="#0b1629",
        tab_bg="#0f1d34",
        tab_fg="#8bcdf4",
        tab_hover_bg="#153458",
        tab_active_bg="#38bdf8",
        tab_active_fg="#08111f",
        tab_border="#2b4f8d",
        entry_bg="#10243d",
        entry_fg="#e2f2ff",
        entry_border="#1e3a6e",
        entry_focus="#38bdf8",
        entry_warning_bg="#2a230f",
        entry_success_bg="#0e2a22",
        entry_info_bg="#0f2e4d",
        card_bg="#0f1d34",
        card_alt_bg="#0c1830",
        card_border="#1c3867",
        card_header_bg="#113559",
        card_header_fg="#ffffff",
        table_header_bg="#38bdf8",
        table_header_fg="#08111f",
        table_bg="#0f1d34",
        table_alt_bg="#0c1830",
        table_selected_bg="#113559",
        table_selected_fg="#e2f2ff",
        scrollbar_bg="#28517f",
        scrollbar_trough="#08111f",
        scrollbar_active="#3e6da8",
        scrollbar_fg="#d2efff",
        button_primary_bg="#38bdf8",
        button_primary_hover="#0ea5e9",
        button_primary_fg="#08111f",
        button_secondary_bg="#10243d",
        button_secondary_hover="#153458",
        button_secondary_fg="#e2f2ff",
        button_success_bg="#34d399",
        button_success_hover="#22c55e",
        button_success_fg="#08111f",
        button_danger_bg="#fb7185",
        button_danger_hover="#f43f5e",
        button_danger_fg="#08111f",
        button_muted_bg="#2b4f8d",
        button_muted_hover="#1e3a6e",
        button_muted_fg="#e2f2ff",
        button_ghost_bg="#0b1629",
        button_ghost_hover="#153458",
        button_ghost_fg="#8bcdf4",
        gpa_card_bg="#0f2e4d",
        gpa_card_fg="#38bdf8",
        grade_card_bg="#0d2a22",
        grade_card_fg="#34d399",
        points_card_bg="#23143d",
        points_card_fg="#a78bfa",
        info_card_bg="#10243d",
        info_card_fg="#8bcdf4",
        strategy_balanced="#38bdf8",
        strategy_progressive="#a78bfa",
        strategy_flexible="#22d3ee",
        strategy_front_loaded="#f59e0b",
    ),
}

THEME_NAMES = list(THEMES.keys())
_current_theme_name = "light"


def set_current_theme(name: str):
    global _current_theme_name
    if name in THEMES:
        _current_theme_name = name


def get_current_theme_name() -> str:
    return _current_theme_name


def get_theme(name: str | None = None):
    chosen = name or _current_theme_name
    return deepcopy(THEMES.get(chosen, THEMES["light"]))
